# shardingshpere 配置
spring:
  shardingsphere:
    datasource:
      names: main,secondary
      main: # 主库配置
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
      secondary: #从库配置
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
    masterslave: # 主从信息配置
      name: ms
      master-data-source-name: main
      slave-data-source-names: secondary
    props:
      sql:
        show: true
