mybatis:
  type-aliases-package: com.github.oliverschen.dynamic.mapper.*
  configuration:
    map-underscore-to-camel-case: true
    local-cache-scope: statement
    cache-enabled: false

### 数据源配置
spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 200
        minimum-idle: 50
    secondary:
      jdbc-url: jdbc:mysql://127.0.0.1:3307/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 200
        minimum-idle: 50






