server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/d_rac?serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false