mybatis:
  type-aliases-package: com.github.oliverschen.mapper.*
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  datasource:
    user1:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/user_1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      password: root
      username: root
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        maximum-pool-size: 200
        minimum-idle: 50
    user2:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/user_2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      password: root
      username: root
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        maximum-pool-size: 200
        minimum-idle: 50
  application:
    name: tcc
dubbo:
  registry:
    address: nacos://localhost:8848
  scan:
    base-packages: com.github.oliverschen
  metadata-report: nacos://localhost:8848

logging:
  level:
    com.github.oliverschen.mapper: trace
