server:
  port: 5259

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/f_account?serverTimezone=Asia/Shanghai
    username: root
    password: root



